version: "3.8"

services:
  spring-petclinic:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
    command: ["java", "-jar", "app.jar", "-Dspring.profiles.active=mysql"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
    
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8082:8081"
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/kmotyczynska/GridDynamics/spring-petclinic/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    ports:
      - "8082:80"
    volumes:
      - /tmp/spring-petclinic.log:/spring-petclinic.log
      - /Users/kmotyczynska/GridDynamics/spring-petclinic/prometheus/promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

volumes:
  nexus-data:
  jenkins_home:
