version: "3.8"

services:
  spring-petclinic:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
    command: ["java", "-jar", "app.jar", "-Dspring.profiles.active=mysql"]
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8082:8081"
volumes:
  nexus-data: {}
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
